<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <?php echo $this->navigation('navigation')->menu()->setPartial('partials/left-menu-user-area'); ?>

        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('PIN'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">

                <!-- module-sharing-resmume -->
                <div class="module-sharing-resmume padding-top">

                    <div style="float: left;">
                        <div class="pin-title">
                            <?= $this->translate('QUESTO &Egrave; IL PIN CHE TI SERVIR&Agrave; PER UTILIZZARE UNA SHARE&#39;NGO'); ?>
                        </div>

                        <div style="width:100%; overflow:hidden">

                            <div id="pin" class="pin-box" style="padding-top: 3px;margin-top: 10px;">
                                <?php echo $this->layout()->loggedUser->getPrimaryPin(); ?>
                            </div>

                            <div class="pin-warning" style="font-size: 16px !important;">
                                <?= $this->translate('ATTENZIONE: MEMORIZZALO IN LUOGO SICURO E NON DARLO AD ALTRI'); ?>
                            </div>

                        </div>

                        <div class="pin-info" style="text-align: center; font-size: 20px; line-height: 2.022287066089143; font-weight: 500;">
                            <a href="http://site.sharengo.it/come-funziona/" style="color: #43a34c;">
                                <i class="fa fa-question-circle"></i>
                                <span style="text-decoration: underline; text-transform: uppercase;"> <?= $this->translate('Guarda come si usa'); ?></span>
                            </a>
                        </div>

                        <div style="min-width: 350px;  min-height: 200px; overflow:hidden;">
                            <div style="padding-bottom: 30px; padding-top: 20px;  text-align:center">
                                <?= $this->translate('Vuoi anche una CARD APRIPORTA associata al tuo account?'); ?><br />
                                <span style="color: #ff0000"><?= $this->translate('CLICCA SULL’IMMAGINE DELLA CARTA'); ?></span> <?= $this->translate('per inoltrare la tua richiesta'); ?>.
                            </div>
                            <div style="margin-top: 10px; max-width: 350px; margin: auto; text-align: center;">
                                <a href="mailto:servizioclienti@sharengo.eu?subject=<?= $this->translate("RICHIESTA DI CARD SHARE&#39;NGO"); ?>">
                                    <img src="/images/carta_web.png" width="150" style="float: left; min-width: 150px; margin-right: 10px;">
                                </a>
                                <a href="mailto:servizioclienti@sharengo.eu?subject=<?= $this->translate("RICHIESTA DI CARD SHARE&#39;NGO"); ?>">
                                    <img src="/images/carta_web_retro.png" width="150" style="min-width: 150px;">
                                </a>
                            </div>
                            <div style="margin-top: 10px; max-width: 350px; margin: auto; text-align: center;">
                                <?= $this->translate("Ti arriver&agrave; su richiesta gratuitamente a casa in una settimana o puoi anche ritirarla c/o i nostri uffici"); ?>.
                            </div>

                        </div>
                    </div>

                </div>
                <!-- module-sharing-resmume -->

            </div>
            <!-- module-column-app-content -->

        </div>
        <!-- module-column-app dx -->

    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->
