<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <?php use BusinessCore\Entity\Business;

        echo $this->navigation('navigation')->menu()->setPartial('partials/left-menu-user-area'); ?>

        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('PIN'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">

                <!-- module-sharing-resmume -->
                <div class="module-sharing-resmume padding-top">

                    <div style="float: left;">
                        <div class="pin-title">
                            <?= $this->translate('QUESTO E’ IL PIN CHE TI SERVIRA’ PER UTILIZZARE PRIVATAMENTE UN’EQUOMOBILE'); ?>
                        </div>

                        <div style="width:100%; overflow:hidden">

                            <div id="pin" class="pin-box">
                                <?php echo $this->layout()->loggedUser->getPrimaryPin(); ?>
                            </div>

                            <div class="pin-warning" style="font-size: 16px !important;">
                                <?= $this->translate('ATTENZIONE: MEMORIZZALO IN LUOGO SICURO E NON DARLO AD ALTRI'); ?>
                            </div>

                        </div>

                        <div class="pin-info">
                            <a href="<?= $this->url('comefunziona'); ?>">
                                <?= $this->translate('Guarda come si usa'); ?>
                            </a>

                            <div style="float: right">
                                <?= $this->translate('Vuoi anche una CARD APRIPORTA associata al tuo account?'); ?><br />
                                <span style="color: #ff0000"><?= $this->translate('CLICCA SULL’IMMAGINE DELLA CARTA'); ?></span> <?= $this->translate('per inoltrare la tua richiesta'); ?>.
                            </div>

                        </div>
                    </div>

                    <?php if (!empty($this->businesses)) { ?>
                        <div style="float: left;">
                            <div class="pin-title">
                                <?= $this->translate('Se hai dimenticato il tuo PIN AZIENDALE dovrai richiederderlo alla tua azienda:'); ?>
                            </div>

                            <?php /** @var Business $business */
                            foreach ($this->businesses as $business) { ?>
                                <ul>
                                    <li>
                                        <?= $this->translate('Nome: ') . $business->getName(); ?>
                                    </li>
                                    <li>
                                        <?= $this->translate('Email: ') . $business->getEmail(); ?>
                                    </li>
                                    <li>
                                        <?= $this->translate('Telefono: ') . $business->getPhone(); ?>
                                    </li>
                                </ul>
                            <?php } ?>
                        </div>
                    <?php } ?>


                    </div>


                    <div></div>


                </div>
                <!-- module-sharing-resmume -->

            </div>
            <!-- module-column-app-content -->

        </div>
        <!-- module-column-app dx -->

    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->
